BOOTLOADER = atmel-dfu
CAPS_WORD_ENABLE = yes
EXTRAKEY_ENABLE = yes

ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes

OLED_ENABLE = yes
OLED_DRIVER = ssd1306

COMBO_ENABLE = yes
MOUSEKEY_ENABLE = yes

COMMAND_ENABLE = no
LTO_ENABLE = yes

RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
SPLIT_KEYBOARD = yes
